# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go/sdk/internal
Version:                1.3.0
%global tag             sdk/internal/v1.3.0

%gometa -f

%global common_description %{expand:
Azure SDK for Go - internal library.}

%global golicenses      NOTICE.txt LICENSE.txt sdk/internal/LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SUPPORT.md\\\
                        SECURITY.md README.md sdk/internal/CHANGELOG.md \\\
                        sdk/internal/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Azure SDK for Go - internal library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

# move building library to the root to match goipath
mv sdk/internal/* .
rm -rf .github documentation eng profile sdk

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
for test in "TestRecordingHTTPClient_Do" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck -d recording
%endif

%gopkgfiles

%changelog
%autochangelog
